new

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -59,12 +59,12 @@ jobs:
 
       - name: terraform plan
         id: plan
-        run: terraform plan -no-color -input=false -out planfile
+        run: terraform plan -out planfile
         #continue-on-error: true
 
-      - name: terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+     # - name: terraform plan status
+      #  if: steps.plan.outcome == 'failure'
+       # run: exit 1
 
       - name: terraform apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
